version: "3.2"

services:
 flask-app:
    image: 127.0.0.1:5003/flask-app:latest
    build: .
    depends_on:
      - flask-mysql
    command: python3 /opt/app.py
    ports:
      - "5001:5000"
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 2
      #endpoint_mode: vip

 flask-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: password
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 1
      #endpoint_mode: dnsrr
networks:
  overlay:
