version: "3"

services:
  flask-app:
    build: .
    command: python3 /opt/app.py
    ports:
      - "8080:5000"
    networks:
      - front-tier
    depends_on:
      - flask-mysql
  flask-mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: todo
      MYSQL_ROOT_PASSWORD: password
    networks:
      - front-tier
networks:
  front-tier:

  # Refeence https://littletechblogger.wordpress.com/2016/03/02/docker-how-to-create-a-custom-database-from-docker-mysql-image/
